sample_time: 0.05
sample_rate: 20.0
history_length: 4
model_name: "gem_e2"
model_states_topic: "/gazebo/model_states"
joint_states_topic: "/joint_states"
state_topic: "/system_id/vehicle_state"
command_topic: "/ackermann_cmd"
command_type: "ackermann_msgs/AckermannDrive"
steering_joint_names: ['left_steering_hinge_joint','right_steering_hinge_joint']
maximum_speed: 5.0
maximum_steering: 0.20
